### ISSUE TITLE
Add encoding to `cjk.rb` for jRuby 1.7.x support

### ISSUE THREAD

**Issue by abelsromero** [chloerei/asciidoctor-pdf-cjk#2]
As commented in https://github.com/jruby/jruby/issues/4360, adding the header `# encoding: utf-8` to https://github.com/chloerei/asciidoctor-pdf-cjk/blob/master/lib/asciidoctor/pdf/cjk.rb ensures compatibility with jRuby 1.7.x.
This means providing compatibility also with other Asciidoctor extensions as well as the standard jRuby version used in AsciidoctorJ 1.5.x.

**Comment by chloerei** [comment]
I pushed a patch, can you test it in your jRuby project? If it passed I will release a patch version.

**Comment by abelsromero** [comment]
Applying the changes in my local installation worked fine :+1:

**Comment by chloerei** [comment]
0.1.3 released. 😘

**Comment by abelsromero** [comment]
Thanks. I'll test my whole example as soon as I can.
